### ISSUE TITLE
Dependency on pixell breaks wheels on MacOS

### ISSUE THREAD

**Issue by tskisner** [simonsobs/so3g#154]
In #152, we introduced a hard dependency on pixell.  However, the [latest version of pixell on PyPI](https://pypi.org/project/pixell/0.19.0/#files) only has wheels for Linux.  This means that on MacOS, pip will attempt to compile pixell, which will likely fail (including during the builds of so3g wheels).  Some options:

- Ask the pixell folks reading this to build wheels for MacOS
- Declare that MacOS is no longer officially supported by the SO software stack
- Remove the pixell hard dependency in so3g and make it optional

Thoughts?

**Comment by mhasself** [comment]
For now let's remove the pixell hard dependency.  You can definitely do a lot of stuff without pixell ...

The tests that need pixell are already guarded so they won't try to run if it isn't available.

pixell should still be included in the docker image, so that the tests do run there.  Not sure what best way to do that is (having packages listed in requirements.txt, but not setup.py, does not seem like the best way, but it's what we were doing until yesterday).

**Comment by tskisner** [comment]
Ok, how about removing pixell from `requirements.txt` and add a new file `dev-requirements.txt` or `test-requirements.txt` with extra or soft dependencies.  Then [in the Dockerfile here](https://github.com/simonsobs/so3g/blob/5d2716e61d9ab3f9a3ec32824c31586daa13250b/Dockerfile#L26) we could install both sets of packages.

**Comment by tskisner** [comment]
Testing this solution in #155

**Comment by tskisner** [comment]
Closed by #155
