### ISSUE TITLE
provider session_id in HkSessionHelper status frame

### ISSUE THREAD

**Issue by jlashner** [simonsobs/so3g#38]
In the HK data files, I think it's a good idea to put provider session_id into the status frames, so you can tell if agents have been restarted without looking into the data frames. I think we can either do this by inserting it into the description or by adding another field to the provider's status object. @BrianJKoopman Does sisock still rely on the description to be a unique identifier for the provider?

**Comment by BrianJKoopman** [comment]
Yes, under the current scheme the description is used for the field names in sisock. Making them update dynamically with a unique session_id would cause the same problem we had when debug timestamps were inserted in the same place -- the drop down menu in grafana's sisock plugin would have a unique name per session_id.

**Comment by mhasself** [comment]
Does the aggregator currently monitor the provider session_id, and does a change in session_id trigger drop and re-add of the provider (i.e. with a new prov_id)?  This is essential for "correct" HK files, since a new provider session could have different fields in the feed.

I agree that it would be nice to actually store the provider session info.  It's easy enough to add stuff into Status.  Perhaps in the near term (this week), we just add "prov_session_id", a G3Int encoded like the agg session_id?

In the slightly longer term (HK schema v1 -- a few weeks), I propose we rename "description" to "feed_name" and create a new field, "detail", with free form text (e.g. "Temperatures for SAT2").

(Migration from schema v0 to v1 will be done in the "upstream" direction -- we can adapt the consumers, such as sisock and friends, first, using a schema translator (basically already written).  Then we change over the producers, such as the aggregator.)

**Comment by mhasself** [comment]
Please re-open if this is still a concern ...
