### ISSUE TITLE
Weather in so3g vs sotodlib?

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/so3g#93]
Noticed this while talking with Jack about requirements. This is the only module that imports `ephem` and doesn't seem to have related C++ code. Is this something we'd also want to move to sotodlib?

https://github.com/simonsobs/so3g/blob/f809ff3708b12b212a113e615ec60de7004add90/python/proj/weather.py#L4

**Comment by mhasself** [comment]
Is your problem that it depends on ephem, or that doesn't make use of C++ code?  This Weather class provides some simple support for the pointing system, which is ~self-contained and very C++.  So it needs to be here, I think.  It may be considered as an interface class rather than something that sotodlib would use internally.

ephem is used in the library _tests_, so I would prefer it to remain a formal requirement.  Perhaps it should be put in requirements.txt ... if the concern is that it's difficult to collect all the right dependencies for so3g efficiently when installing on new systems.

We could use astropy instead of ephem, for the pointing tests; but there are probably better things to work on than replacing working things with working things!
